kind: MutatingWebhookConfiguration
apiVersion: admissionregistration.k8s.io/v1
metadata:
  name: serviceMutator
  annotations:
    cert-manager.io/inject-ca-from: default/client
webhooks:
  - name: serviceMutator

    objectSelector:
      matchExpressions:
        - key: serviceMutator
          operator: Exists
    failurePolicy: ignore
    clientConfig:
      service:
        namespace: default
        name: mutating-webhook
        path: /mutate
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["services"]
        operations: ["CREATE", "UPDATE"]
        scope: Namespaced
    sideEffects: None
    admissionReviewVersions: ["v1"]
